library:
  source-dirs: src
tests:
  hub-board-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - hub-board
copyright: 2019 Author name here
maintainer: example@example.com
dependencies:
  - MissingH
  - yaml
  - text
  - http-client
  - http-client-tls
  - http-types
  - lens
  - lens-aeson
  - aeson
  - bytestring
  - directory
  - base >= 4.7 && < 5
  - either
  - time
  - split
  - utf8-string
name: hub-board
version: 0.1.0.0
extra-source-files:
  - README.md
  - ChangeLog.md
author: Author name here
github: githubuser/hub-board
license: BSD3
executables:
  hub-board-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - hub-board
description: >-
  Please see the README on GitHub at
  <https://github.com/githubuser/hub-board#readme>
