library:
  source-dirs: src
tests:
  hub-board-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - hub-board
copyright: 2019 suzuki-hoge
maintainer: foo@bar.com
dependencies:
  - MissingH
  - yaml
  - text
  - http-client
  - http-client-tls
  - http-types
  - lens
  - lens-aeson
  - aeson
  - bytestring
  - directory
  - base >= 4.7 && < 5
  - either
  - time
  - split
  - utf8-string
  - optparse-applicative
  - hspec
name: hub-board
version: 2.2.1
extra-source-files:
  - README.md
  - ChangeLog.md
author: suzuki-hoge
github: suzuki-hoge/hub-board
license: BSD3
executables:
  hub-board:
    source-dirs: app
    main: Main.hs
    ghc-options:
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - hub-board
description: >-
  Please see the README on GitHub at
  <https://github.com/suzuki-hoge/hub-board#readme>
